apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shortener-admin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: shortener
    server: https://kubernetes.default.svc
  sources:
    - repoURL: registry-1.docker.io/phucapps
      chart: shortener-admin
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/manifests/shortener-admin/debug-values.yaml
        valuesObject:
          admin:
            replicaCount: 2
            jobs:
              useIstio: true
    - repoURL: https://github.com/nguyenminh-phuc/scalable-url-shortener/
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
