apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-pre-install" (include "shortener-admin.fullname" .) }}
  labels:
    {{- include "shortener-admin.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-pre-install" (include "shortener-admin.fullname" .) }}
  labels:
    {{- include "shortener-admin.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
    resourceNames:
      - {{ .Values.rabbitmq.secret }}
      - {{ .Values.redis.secret }}
      - {{ .Values.admin.web.basicAuthSecret }}
      {{- if (include "shortener-admin.isRelease" .) }}
      {{- $postgresql_ha := index .Values "postgresql-ha" }}
      - {{ $postgresql_ha.postgresql.existingSecret }}
      - {{ $postgresql_ha.pgpool.existingSecret }}
      {{- else }}
      - {{ .Values.postgresql.auth.existingSecret }}
      {{- end }}
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch" ]
    resourceNames:
      {{- $trustManager := index .Values "trust-manager" }}
      - {{ $trustManager.deploymentName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-pre-install" (include "shortener-admin.fullname" .) }}
  labels:
    {{- include "shortener-admin.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-pre-install" (include "shortener-admin.fullname" .) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ printf "%s-pre-install" (include "shortener-admin.fullname" .) }}
  apiGroup: rbac.authorization.k8s.io
