apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shortener-admin.serviceAccountName" . }}
  labels:
    {{- include "shortener-admin.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "shortener-admin.serviceAccountName" . }}
  labels:
    {{- include "shortener-admin.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "statefulsets" ]
    verbs: [ "get", "list", "watch" ]
    resourceNames:
      - {{ .Values.zookeeper.statefulSetName }}
      - {{ .Values.rabbitmq.statefulSetName }}
      - {{ .Values.redis.statefulSetName }}
      {{- if (include "shortener-admin.isRelease" .) }}
      - {{ printf "%s-postgresql-ha-postgresql" (include "shortener-admin.fullname" .) }}
      - {{ printf "%s-postgresql-ha-pgpool" (include "shortener-admin.fullname" .) }}
      {{- else }}
      - {{ printf "%s-postgresql" (include "shortener-admin.fullname" .) }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "shortener-admin.serviceAccountName" . }}
  labels:
    {{- include "shortener-admin.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shortener-admin.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "shortener-admin.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
