apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-validate-secrets" (include "shortener-admin.fullname" .) }}
  labels:
    {{- include "shortener-admin.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 3
  template:
    metadata:
      name: {{ printf "%s-validate-secrets" (include "shortener-admin.fullname" .) }}
    spec:
      serviceAccountName: {{ printf "%s-pre-install" (include "shortener-admin.fullname" .) }}
      containers:
        - name: validate-secrets
          image: {{ .Values.admin.jobs.kubectl }}
          {{- if .Values.admin.jobs.useIstio }}
          securityContext:
            runAsUser: 1337
          {{- end }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
{{ include "shortener-admin.useIstio" . | indent 14 }}
{{ include "shortener-admin.checkSecret" (dict "name" .Values.rabbitmq.secret "namespace" .Release.Namespace) | indent 14 }}
{{ include "shortener-admin.checkSecret" (dict "name" .Values.redis.secret "namespace" .Release.Namespace) | indent 14 }}
{{ include "shortener-admin.checkSecret" (dict "name" .Values.admin.web.basicAuthSecret "namespace" .Release.Namespace) | indent 14 }}
{{- if (include "shortener-admin.isRelease" .) }}
{{ $postgresql_ha := index .Values "postgresql-ha" }}
{{ include "shortener-admin.checkSecret" (dict "name" $postgresql_ha.postgresql.existingSecret "namespace" .Release.Namespace) | indent 14 }}
{{ include "shortener-admin.checkSecret" (dict "name" $postgresql_ha.pgpool.existingSecret "namespace" .Release.Namespace) | indent 14 }}
{{- else }}
{{ include "shortener-admin.checkSecret" (dict "name" .Values.postgresql.auth.existingSecret "namespace" .Release.Namespace) | indent 14 }}
{{- end }}
              echo "Done."
      restartPolicy: Never
