{{- if .Values.frontend.rest.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ printf "%s-rest" (include "shortener-frontend.fullname" .) }}
  labels:
    {{- include "shortener-frontend.restLabels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.frontend.rest.gateway.className }}
  listeners:
    - name: https
      hostname: {{ .Values.frontend.rest.gateway.host }}
      port: {{ .Values.frontend.rest.gateway.port }}
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.frontend.rest.gateway.certificateSecret }}
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-rest" (include "shortener-frontend.fullname" .) }}
  labels:
    {{- include "shortener-frontend.restLabels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ printf "%s-rest" (include "shortener-frontend.fullname" .) }}
  hostnames: [{{ .Values.frontend.rest.gateway.host }}]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ printf "%s-rest" (include "shortener-frontend.fullname" .) }}
          port: {{ .Values.frontend.service.port }}
{{- end -}}
