apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shortener-frontend.serviceAccountName" . }}
  labels:
    {{- include "shortener-frontend.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "shortener-frontend.serviceAccountName" . }}
  labels:
    {{- include "shortener-frontend.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "statefulsets" ]
    verbs: [ "get", "list", "watch" ]
    resourceNames:
      - {{ .Values.zookeeper.statefulSetName }}
      - {{ .Values.redis.statefulSetName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "shortener-frontend.serviceAccountName" . }}
  labels:
    {{- include "shortener-frontend.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shortener-frontend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "shortener-frontend.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
