apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
  labels:
    {{- include "shortener-frontend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
  labels:
    {{- include "shortener-frontend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
    resourceNames:
      - {{ .Values.redis.secret }}
      {{- if .Values.frontend.acme.enabled }}
      - {{ .Values.frontend.acme.secret.name }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
  labels:
    {{- include "shortener-frontend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
  apiGroup: rbac.authorization.k8s.io
