apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
  labels:
    {{- include "shortener-frontend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 3
  template:
    metadata:
      name: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
    spec:
      serviceAccountName: {{ printf "%s-validate-secrets" (include "shortener-frontend.fullname" .) }}
      containers:
        - name: validate-secrets
          image: {{ .Values.frontend.jobs.kubectl }}
          {{- if .Values.frontend.jobs.useIstio }}
          securityContext:
            runAsUser: 1337
          {{- end }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
{{ include "shortener-frontend.useIstio" . | indent 14 }}
{{ include "shortener-frontend.checkSecret" (dict "name" .Values.redis.secret "namespace" .Release.Namespace) | indent 14 }}
{{- if .Values.frontend.acme.enabled }}
{{ include "shortener-frontend.checkSecret" (dict "name" .Values.frontend.acme.secret.name "namespace" .Release.Namespace) | indent 14 }}
{{- end }}
              echo "Done."
      restartPolicy: Never
