debug: true
release: false

admin:
  image:
    tag: latest
  replicaCount: 1
  service:
    headless: false
  serviceMonitor:
    enabled: false
    namespace: monitoring
    labels: { }
  otlpExporter:
    enabled: false
    endpoint: ""
  web:
    aspEnvironment: Development
  bannedDomains: [ banned.example.com ]
  jobs:
    useIstio: false

zookeeper:
  replicaCount: 1

redis:
  statefulSetName: shortener-shared-redis-master
  serviceName: shortener-shared-redis-master
