{{- if .Values.shared.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-selfsigned-issuer" (include "shortener-shared.fullname" .) }}
  labels:
    {{- include "shortener-shared.labels" . | nindent 4 }}
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-selfsigned-ca" (include "shortener-shared.fullname" .) }}
  labels:
    {{- include "shortener-shared.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ printf "%s-selfsigned-ca" (include "shortener-shared.fullname" .) }}
  secretName: {{ printf "%s-root" (include "shortener-shared.fullname" .) }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ printf "%s-selfsigned-issuer" (include "shortener-shared.fullname" .) }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-ca-issuer" (include "shortener-shared.fullname" .) }}
  labels:
    {{- include "shortener-shared.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ printf "%s-root" (include "shortener-shared.fullname" .) }}
{{- end -}}
