apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-validate-secrets" (include "shortener-shared.fullname" .) }}
  labels:
    {{- include "shortener-shared.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    metadata:
      name: {{ printf "%s-validate-secrets" (include "shortener-shared.fullname" .) }}
    spec:
      serviceAccountName: {{ printf "%s-validate-secrets" (include "shortener-shared.fullname" .) }}
      containers:
        - name: validate-secrets
          image: {{ .Values.shared.jobs.kubectl }}
          {{- if .Values.shared.jobs.useIstio }}
          securityContext:
            runAsUser: 1337
          {{- end }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
{{ include "shortener-shared.useIstio" . | indent 14 }}
{{ include "shortener-shared.checkSecret" (dict "name" .Values.rabbitmq.auth.existingPasswordSecret "namespace" .Release.Namespace) | indent 14 }}
{{- if (include "shortener-shared.isRelease" .) }}
{{ $redis_cluster := index .Values "redis-cluster" }}
{{ include "shortener-shared.checkSecret" (dict "name" $redis_cluster.existingSecret "namespace" .Release.Namespace) | indent 14 }}
{{- else }}
{{ include "shortener-shared.checkSecret" (dict "name" .Values.redis.auth.existingSecret "namespace" .Release.Namespace) | indent 14 }}
{{- end }}
              echo "Done."
      restartPolicy: Never
